package com.juzizhen.rcode.sql.model;

import java.time.Instant;
import java.util.Optional;

public class RedemptionCode {
    private int id;
    private String code;
    private String itemJson;
    private int usesLeft;
    private int maxUses;
    private Optional<Long> expirationDate; // Unix timestamp
    private Instant createdAt;

    public RedemptionCode(int id, String code, String itemJson, int usesLeft, int maxUses, Optional<Long> expirationDate, Instant createdAt) {
        this.id = id;
        this.code = code;
        this.itemJson = itemJson;
        this.usesLeft = usesLeft;
        this.maxUses = maxUses;
        this.expirationDate = expirationDate;
        this.createdAt = createdAt;
    }

    // Constructor for creating new codes (ID and createdAt will be generated by DB)
    public RedemptionCode(String code, String itemJson, int usesLeft, int maxUses, Optional<Long> expirationDate) {
        this(0, code, itemJson, usesLeft, maxUses, expirationDate, Instant.now());
    }

    public int getId() {
        return id;
    }

    public String getCode() {
        return code;
    }

    public String getItemJson() {
        return itemJson;
    }

    public int getUsesLeft() {
        return usesLeft;
    }

    public int getMaxUses() {
        return maxUses;
    }

    public Optional<Long> getExpirationDate() {
        return expirationDate;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setUsesLeft(int usesLeft) {
        this.usesLeft = usesLeft;
    }

    @Override
    public String toString() {
        return "RedemptionCode{" +
               "id=" + id +
               ", code='" + code + '\'' +
               ", itemJson='" + itemJson + '\'' +
               ", usesLeft=" + usesLeft +
               ", maxUses=" + maxUses +
               ", expirationDate=" + expirationDate +
               ", createdAt=" + createdAt +
               '}';
    }
}
