package com.juzizhen.rcode.sql.model;

import java.time.Instant;
import java.util.UUID;

public class RedeemedHistory {
    private final int id;
    private final int codeId;
    private final UUID playerUuid;
    private final String playerName;
    private final Instant redeemedAt;

    public RedeemedHistory(int id, int codeId, UUID playerUuid, String playerName, Instant redeemedAt) {
        this.id = id;
        this.codeId = codeId;
        this.playerUuid = playerUuid;
        this.playerName = playerName;
        this.redeemedAt = redeemedAt;
    }

    // Constructor for creating new history entries (ID and redeemedAt will be generated by DB)
    public RedeemedHistory(int codeId, UUID playerUuid, String playerName) {
        this(0, codeId, playerUuid, playerName, Instant.now());
    }

    public int getId() {
        return id;
    }

    public int getCodeId() {
        return codeId;
    }

    public UUID getPlayerUuid() {
        return playerUuid;
    }

    public String getPlayerName() {
        return playerName;
    }

    public Instant getRedeemedAt() {
        return redeemedAt;
    }

    @Override
    public String toString() {
        return "RedeemedHistory{" +
               "id=" + id +
               ", codeId=" + codeId +
               ", playerUuid=" + playerUuid +
               ", playerName='" + playerName + '\'' +
               ", redeemedAt=" + redeemedAt +
               '}';
    }
}
